# Generated by Django 3.2 on 2023-05-01 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorite',
            old_name='products',
            new_name='books',
        ),
    ]
